provider:

  endpoints:

    - https://nitter.poast.org
    - https://xcancel.com
    - https://nitter.net
    - https://nitter.no-logs.com
    - https://nitter.privacydev.net
    - https://nitter.tiekoetter.com
    - https://nitter.miningtcup.me
    - nitter.privacyredirect.com 
    - nuku.trabun.org 
    - nitter.meowing.monster 
    - nitter.xitter.cc 
    - nitter.jaydenha.uk 
    - x.n0g.xyz 
    - tw.eir-nya.gay

http:

  timeout: 20

rss:

  output: output/feeds/

  processed_output: output/feeds_processed/
