provider:

  endpoints:

    - https://nitter.poast.org
    - https://xcancel.com
    - https://nitter.privacydev.net
    - https://nitter.tiekoetter.com

http:

  timeout: 20

rss:

  output: feeds/
